# Data Ingestion Service Configuration
# Phase 6: Money Flow & Screener Implementation

# Service
service:
  host: "0.0.0.0"
  port: 8500
  name: "data-ingestion"
  version: "1.0.0"

# NATS
nats_url: "nats://nats:4222"
use_jetstream: true

# Market Data Source Selection
# Options: "alpaca" (FREE real-time, 30 symbol limit) or "ibkr" (unlimited symbols)
market_data_source: "ibkr"

# Symbols Configuration (shared by all market data sources)
# Organized by tier for sector rotation analysis
# NOTE: IBKR = UNLIMITED symbols (using paper trading account)
symbols:
  # TIER 1: Core Sector ETFs (SPDR X-Series - Macro Rotation Map) - 11 symbols
  sector_etfs:
    - XLK  # Technology
    - XLV  # Healthcare
    - XLF  # Financials
    - XLY  # Consumer Discretionary
    - XLI  # Industrials
    - XLP  # Consumer Staples
    - XLE  # Energy
    - XLB  # Materials
    - XLRE # Real Estate
    - XLU  # Utilities
    - XLC  # Communication Services

  # TIER 1: Benchmarks - 4 symbols
  benchmark_etfs:
    - SPY  # S&P 500
    - QQQ  # Nasdaq 100
    - IWM  # Russell 2000
    - DIA  # Dow Jones

  # TIER 2: Sub-Sector / Industry ETFs (Early Sector Indicators) - ALL 23 symbols
  subsector_etfs:
    # Technology Sub-Sectors (XLK early indicators)
    - SMH   # Semiconductors (leads tech by 2-4 weeks)
    - SOXX  # Semiconductor Alt
    - XSD   # Semiconductor Small-Cap

    # Financials Sub-Sectors (XLF early indicators)
    - KBE   # Banks
    - KRE   # Regional Banks
    - IYG   # Diversified Financials

    # Consumer Discretionary Sub-Sectors (XLY early indicators)
    - CARZ  # Autos
    - ITB   # Homebuilders (housing sensitive)
    - PEJ   # Leisure & Entertainment

    # Industrials Sub-Sectors (XLI early indicators)
    - ITA   # Aerospace & Defense
    - IYT   # Transportation (Dow Theory confirmation)

    # Energy Sub-Sectors (XLE early indicators)
    - OIH   # Oil Services
    - XOP   # Oil & Gas Exploration (high beta)

    # Materials Sub-Sectors (XLB early indicators)
    - SLX   # Steel
    - COPX  # Copper Miners
    - WOOD  # Timber

    # Healthcare Sub-Sectors (XLV early indicators)
    - IBB   # Biotech (risk appetite gauge)
    - XPH   # Pharmaceuticals

    # Communication Sub-Sectors (XLC early indicators)
    - FDN   # Internet
    - SOCL  # Social Media

    # Utilities Sub-Sectors (XLU confirmation)
    - PUI   # Power Utilities

    # Real Estate Sub-Sectors (XLRE confirmation)
    - IYR   # Real Estate Alt
    - REZ   # Residential Real Estate

  # TIER 3: Thematic / Innovation ETFs (Preemptive Rotation Signals) - 18 symbols
  thematic_etfs:
    # AI & Innovation (Tech/Discretionary momentum)
    - ARKK  # ARK Innovation
    - AIQ   # AI Powered Equity
    - BOTZ  # Robotics & Automation

    # Clean Energy (Energy/Industrials/Materials ESG proxy)
    - ICLN  # Clean Energy
    - TAN   # Solar Energy
    - PBW   # Clean Energy Alt

    # Cybersecurity (Tech defensive-growth theme)
    - HACK  # Cybersecurity
    - CIBR  # Cybersecurity Alt

    # Cloud & Software (Tech margin expansion)
    - CLOU  # Cloud Computing
    - WCLD  # Cloud Computing Alt
    - SKYY  # Cloud Computing 2

    # Fintech (Financials digital proxy)
    - FINX  # Fintech Innovation
    - IPAY  # Mobile Payments

    # Infrastructure (Industrials/Materials fiscal expansion)
    - PAVE  # Infrastructure
    - IFRA  # Infrastructure Alt

    # Defense (Industrials geopolitical)
    - DFEN  # Defense

  # TIER 4: Commodities & Real Assets (Inflation Hedges) - 8 symbols
  commodity_etfs:
    # Broad Commodities
    - DBC   # Commodities Broad Basket
    - PICK  # Metals & Mining
    - DBB   # Base Metals

    # Precious Metals
    - GLD   # Gold
    - SLV   # Silver
    - PPLT  # Platinum

    # Real Estate (rate-sensitive real assets)
    - VNQ   # Vanguard Real Estate
    - REET  # Real Estate Alt

  # TIER 5: Niche & Thematic ETFs (Early Signal Probes & Narrative Acceleration) - 107 symbols
  niche_thematic_etfs:
    # Technology & Innovation (Disruptive / AI / Cloud / Cyber)
    - ARKW  # ARK Next Generation Internet
    - ARKF  # ARK Fintech Innovation
    - ROBO  # Robotics & Automation Alt
    - KOMP  # Future Tech & Innovation
    - XT    # Exponential Technologies
    - SNSR  # Internet of Things
    - DRIV  # Autonomous Vehicles
    - IDRV  # Electric Vehicles Alt
    - QCLN  # Clean Energy Alt
    - LIT   # Lithium & Battery Tech
    - BATT  # Battery Tech & Materials

    # Sustainability, Climate & ESG
    - ACES  # Clean Energy Alt 2
    - GRID  # Smart Power Grids
    - BUGZ  # Clean Energy Bugs
    - CGW   # Water Resources
    - FIW   # Water Alt
    - KRBN  # Carbon Credits
    - GRN   # Green Bonds
    - CO2   # Carbon Offset
    - SMOG  # Low-Carbon Energy
    - RNRG  # Renewable Energy Alt

    # Industrial, Materials & Commodities (Metals, Mining, Agri)
    - REMX  # Rare Earth / Strategic Metals
    - URA   # Uranium & Nuclear
    - NLR   # Nuclear Energy
    - URNM  # Uranium Miners
    - CUT   # Timber & Forestry
    - GDX   # Gold Miners
    - GDXJ  # Junior Gold Miners
    - SIL   # Silver Miners
    - SILJ  # Junior Silver Miners
    - PDBC  # Broad Commodities Alt
    - WEAT  # Wheat
    - CORN  # Corn
    - SOYB  # Soybeans
    - JJE   # Energy Commodities
    - JO    # Coffee
    - NIB   # Cocoa
    - CANE  # Sugar
    - IEO   # Oil & Gas Exploration Alt
    - PSCE  # Energy Exploration Small Cap

    # Financial & Alternative Assets (Cannabis, Crypto, REITs, Yield)
    - KBWB  # Banks Alt
    - MJ    # Cannabis
    - MSOS  # US Cannabis
    - YOLO  # Cannabis Alt
    - PSY   # Psychedelics
    - PSIL  # Psychedelics Alt
    - SRVR  # Data Center REITs
    - DATA  # Data Center Alt
    - HOMZ  # Homebuilders Alt
    - QYLD  # Covered Call Yield (QQQ)
    - JEPI  # Equity Premium Income
    - BITO  # Bitcoin Futures
    - WGMI  # Crypto Alt
    - BLOK  # Blockchain Infrastructure
    - BKCH  # Blockchain Alt
    - GFOF  # Digital Assets
    - DEFI  # DeFi Infrastructure
    - CRYP  # Crypto Alt 2
    - NFTZ  # NFTs & Digital Collectibles
    - SPCX  # SPACs

    # Consumer, Lifestyle & Culture (Gaming, Travel, Vice, Pets)
    - MILN  # Millennials
    - GENY  # Gen Y Consumer
    - AWAY  # Travel & Leisure
    - USAI  # American Consumer
    - BETZ  # Sports Betting & Gaming
    - HERO  # Gaming & Esports
    - NERD  # Gaming & Streaming
    - ESPO  # Esports Alt
    - VICE  # Vice Industries
    - BETS  # Betting Alt
    - EATZ  # Food & Beverage
    - PBJ   # Food & Beverage Alt
    - LUXE  # Luxury Goods
    - BOSS  # Luxury Alt
    - FNDX  # Fashion & Retail
    - BFIT  # Health & Fitness
    - EDOC  # Telemedicine
    - WELL  # Healthcare Wellness
    - PETZ  # Pet Care
    - PAWZ  # Pet Care Alt

    # Human Capital & Social / Demographic Themes
    - SHE   # Gender Equality
    - WOMN  # Women's Leadership
    - HART  # Faith-Based Investing
    - CATH  # Catholic Values
    - EDUT  # Education Technology
    - LRNZ  # Education Alt
    - PINK  # Women's Healthcare
    - CHNA  # Healthcare Alt
    - BBSA  # Values-Based Alt
    - BIBL  # Faith Values Alt
    - YALL  # Southern Values

    # Frontier / Geopolitical / Specialty (Space, Defense, Shipping)
    - UFO   # Space Exploration
    - ROKT  # Space Alt
    - DEF   # Defense Alt
    - XAR   # Aerospace & Defense Alt
    - KSEA  # Global Shipping
    - SEA   # Shipping Alt
    - TOLZ  # Energy Infrastructure MLPs
    - EMLP  # Energy MLPs Alt
    - GLBL  # Global Themes
    - KMED  # Emerging Markets Alt
    - ISRA  # Israel
    - TUR   # Turkey
    - EPHE  # Philippines
    - GOVZ  # Treasury Strips (Duration)
    - SHYF  # Short Duration
    - TIPZ  # TIPS (Inflation Protection)

# Alpaca Configuration (FREE real-time market data)
alpaca:
  api_key_env: "ALPACA_API_KEY"
  secret_key_env: "ALPACA_SECRET_KEY"
  paper: true  # Paper trading account (free real-time data)
  feed: "iex"  # Free IEX data feed

# IBKR Configuration
# NOTE: Paper trading accounts have a ~100-123 symbol subscription limit
# See IBKR_SUBSCRIPTION_LIMIT_ANALYSIS.md for details
# Current: 169 symbols configured, ~123 will subscribe (46 Tier 5 symbols fail)
# Tiers 1-4 (62 symbols) fully operational, Tier 5 (107 symbols) partial coverage
ibkr:
  host: "host.docker.internal"  # Docker -> Host networking
  port: 7497  # IB Gateway PAPER TRADING port (4002 for live, 7497 for paper)
  client_id: 10
  reconnect_delay_seconds: 10
  max_reconnect_attempts: 999999  # Infinite reconnection (handles IB Gateway auto-shutdown)

  # Data subscriptions
  subscribe:
    level1: true
    level2: false  # Order book (10 levels) - REQUIRES PAID SUBSCRIPTION ($10-15/mo per exchange)
    time_and_sales: false  # Time & Sales - REQUIRES PAID SUBSCRIPTION

  # Timeframe Aggregation (from tick data)
  # Used for different trading styles
  timeframes:
    # INTRADAY SWINGS (Scalping, Day Trading)
    intraday:
      - 1m   # 1 minute bars - scalping, very short-term
      - 5m   # 5 minute bars - day trading, intraday patterns
      - 15m  # 15 minute bars - intraday swings, momentum

    # SHORT-TERM SWINGS (Swing Trading, Few Days to Weeks)
    short_term:
      - 30m  # 30 minute bars - short-term swings
      - 1h   # 1 hour bars - hourly trends
      - 4h   # 4 hour bars - intraday/multi-day patterns

    # MEDIUM-TERM SWINGS (Weeks to Months)
    medium_term:
      - 1d   # Daily bars - swing trading, trend following
      - 1w   # Weekly bars - weekly patterns, medium-term trends

    # POSITIONAL TRADES (Months to Years)
    positional:
      - 1d   # Daily bars - position trading
      - 1w   # Weekly bars - long-term trends
      - 1mo  # Monthly bars - very long-term, institutional

  # Enable aggregation (requires TimescaleDB or aggregation service)
  enable_aggregation: true
  aggregation_delay_seconds: 5  # Wait 5 seconds before closing a bar

# FRED API Configuration
fred:
  api_key_env: "FRED_API_KEY"
  base_url: "https://api.stlouisfed.org/fred"
  update_interval_minutes: 60

  # Economic indicators
  series:
    - VIXCLS        # VIX volatility
    - GS10          # 10-year Treasury
    - GS2           # 2-year Treasury
    - T10Y2Y        # Yield curve spread
    - BAMLH0A0HYM2  # High yield spread
    - TEDRATE       # TED spread
    - DFF           # Fed funds rate

# Crypto Configuration
crypto:
  binance:
    base_url: "https://api.binance.com"
    symbols:
      - BTCUSDT
      - ETHUSDT

  alternative_me:
    fear_greed_url: "https://api.alternative.me/fng/"
    update_interval_minutes: 30

  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    update_interval_minutes: 60

# Data Stores
stores:
  questdb:
    url: "http://questdb:9000"
    ilp_host: "questdb"
    ilp_port: 9009

  clickhouse:
    url: "http://clickhouse:8123"
    database: "trade2026"

  valkey:
    host: "valkey"
    port: 6379
    db: 0
    ttl_seconds: 300  # 5 minutes for real-time data

# Circuit Breakers
circuit_breakers:
  consecutive_failures: 3
  cooldown_seconds: 30
  half_open_max_calls: 2

# Retry Strategy (Exponential Backoff)
retry:
  max_attempts: 5
  initial_delay_seconds: 1
  max_delay_seconds: 60
  exponential_base: 2

# Logging
logging:
  level: "INFO"
  format: "json"

# Health Check
health_check:
  enabled: true
  interval_seconds: 30

# Yahoo Finance Configuration (Hybrid Solution for IBKR Limit)
# Handles 46 Tier 5 symbols that exceeded IBKR paper trading subscription limit
yahoo:
  enabled: true
  poll_interval_seconds: 5  # Poll every 5 seconds (Yahoo has no strict rate limits for basic quotes)
  max_retries: 3
  timeout_seconds: 10

  # Symbols to fetch from Yahoo (those that failed IBKR Error 101)
  # These are the 46 Tier 5 symbols that exceeded IBKR paper trading limit
  symbols:
    - AWAY   # Travel & Leisure
    - BETZ   # Sports Betting & Gaming
    - BIBL   # Faith Values Alt
    - BITO   # Bitcoin Futures
    - BKCH   # Blockchain Alt
    - BLOK   # Blockchain Infrastructure
    - CATH   # Catholic Values
    - DEFI   # DeFi Infrastructure
    - EATZ   # Food & Beverage
    - EMLP   # Energy MLPs Alt
    - EPHE   # Philippines
    - ESPO   # Esports Alt
    - FNDX   # Fashion & Retail
    - GLBL   # Global Themes
    - GOVZ   # Treasury Strips (Duration)
    - HERO   # Gaming & Esports
    - HOMZ   # Homebuilders Alt
    - ISRA   # Israel
    - JEPI   # Equity Premium Income
    - LRNZ   # Education Alt
    - LUXE   # Luxury Goods
    - MILN   # Millennials
    - NERD   # Gaming & Streaming
    - PAWZ   # Pet Care Alt
    - PBJ    # Food & Beverage Alt
    - PETZ   # Pet Care
    - PINK   # Women's Healthcare
    - PSIL   # Psychedelics Alt
    - QYLD   # Covered Call Yield (QQQ)
    - ROKT   # Space Alt
    - SEA    # Shipping Alt
    - SHE    # Gender Equality
    - SPCX   # SPACs
    - SRVR   # Data Center REITs
    - TIPZ   # TIPS (Inflation Protection)
    - TOLZ   # Energy Infrastructure MLPs
    - TUR    # Turkey
    - UFO    # Space Exploration
    - USAI   # American Consumer
    - VICE   # Vice Industries
    - WELL   # Healthcare Wellness
    - WGMI   # Crypto Alt
    - WOMN   # Women's Leadership
    - XAR    # Aerospace & Defense Alt
    - YALL   # Southern Values
    - YOLO   # Cannabis Alt
