# Docker Compose for Trade2026 Backend Services
# 8 Python Flask microservices with unified data fetcher
# All services are INTERNAL-ONLY (no exposed ports)
# Access via API Gateway at http://localhost/api/*

version: '3.8'

networks:
  frontend:
    name: trade2026-frontend
    external: true
  backend:
    name: trade2026-backend
    external: true
  lowlatency:
    name: trade2026-lowlatency
    external: true

services:
  # =========================================================================
  # Portfolio Optimization Service (Internal Port 5000)
  # =========================================================================
  portfolio-optimizer:
    build:
      context: ../../backend
      dockerfile: Dockerfile.backend-service
      args:
        SERVICE_NAME: portfolio_optimizer
    container_name: trade2026-portfolio-optimizer
    hostname: trade2026-portfolio-optimizer
    networks:
      - frontend
      - backend
      - lowlatency
    environment:
      - SERVICE_NAME=Portfolio Optimizer
      - SERVICE_PORT=5000
      - QUESTDB_URL=http://questdb:9000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=PathPrefix(`/api/portfolio`)"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.services.portfolio.loadbalancer.server.port=5000"
      - "traefik.docker.network=trade2026-frontend"

  # =========================================================================
  # RL Trading Service (Port 5002)
  # =========================================================================
  rl-trading:
    build:
      context: ../../backend
      dockerfile: Dockerfile.backend-service
      args:
        SERVICE_NAME: rl_trading
    container_name: trade2026-rl-trading
    hostname: trade2026-rl-trading
    ports:
      - "5002:5000"
    networks:
      - frontend
      - backend
      - lowlatency
    environment:
      - SERVICE_NAME=RL Trading
      - SERVICE_PORT=5000
      - QUESTDB_URL=http://questdb:9000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rl-trading.rule=PathPrefix(`/api/rl`)"
      - "traefik.http.routers.rl-trading.entrypoints=web"
      - "traefik.http.services.rl-trading.loadbalancer.server.port=5000"
      - "traefik.docker.network=trade2026-frontend"

  # =========================================================================
  # Advanced Backtest Service (Port 5003)
  # =========================================================================
  advanced-backtest:
    build:
      context: ../../backend
      dockerfile: Dockerfile.backend-service
      args:
        SERVICE_NAME: advanced_backtest
    container_name: trade2026-advanced-backtest
    hostname: trade2026-advanced-backtest
    ports:
      - "5003:5000"
    networks:
      - frontend
      - backend
      - lowlatency
    environment:
      - SERVICE_NAME=Advanced Backtest
      - SERVICE_PORT=5000
      - QUESTDB_URL=http://questdb:9000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backtest.rule=PathPrefix(`/api/backtest`)"
      - "traefik.http.routers.backtest.entrypoints=web"
      - "traefik.http.services.backtest.loadbalancer.server.port=5000"
      - "traefik.docker.network=trade2026-frontend"

  # =========================================================================
  # Factor Models Service (Port 5004)
  # =========================================================================
  factor-models:
    build:
      context: ../../backend
      dockerfile: Dockerfile.backend-service
      args:
        SERVICE_NAME: factor_models
    container_name: trade2026-factor-models
    hostname: trade2026-factor-models
    ports:
      - "5004:5000"
    networks:
      - frontend
      - backend
      - lowlatency
    environment:
      - SERVICE_NAME=Factor Models
      - SERVICE_PORT=5000
      - QUESTDB_URL=http://questdb:9000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.factors.rule=PathPrefix(`/api/factors`)"
      - "traefik.http.routers.factors.entrypoints=web"
      - "traefik.http.services.factors.loadbalancer.server.port=5000"
      - "traefik.docker.network=trade2026-frontend"

  # =========================================================================
  # Simulation Engine Service (Port 5005)
  # =========================================================================
  simulation-engine:
    build:
      context: ../../backend
      dockerfile: Dockerfile.backend-service
      args:
        SERVICE_NAME: simulation_engine
    container_name: trade2026-simulation-engine
    hostname: trade2026-simulation-engine
    ports:
      - "5005:5000"
    networks:
      - frontend
      - backend
      - lowlatency
    environment:
      - SERVICE_NAME=Simulation Engine
      - SERVICE_PORT=5000
      - QUESTDB_URL=http://questdb:9000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simulation.rule=PathPrefix(`/api/simulation`)"
      - "traefik.http.routers.simulation.entrypoints=web"
      - "traefik.http.services.simulation.loadbalancer.server.port=5000"
      - "traefik.docker.network=trade2026-frontend"

  # =========================================================================
  # Fractional Differentiation Service (Port 5006)
  # =========================================================================
  fractional-diff:
    build:
      context: ../../backend
      dockerfile: Dockerfile.backend-service
      args:
        SERVICE_NAME: fractional_diff
    container_name: trade2026-fractional-diff
    hostname: trade2026-fractional-diff
    ports:
      - "5006:5000"
    networks:
      - frontend
      - backend
      - lowlatency
    environment:
      - SERVICE_NAME=Fractional Differentiation
      - SERVICE_PORT=5000
      - QUESTDB_URL=http://questdb:9000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fracdiff.rule=PathPrefix(`/api/fracdiff`)"
      - "traefik.http.routers.fracdiff.entrypoints=web"
      - "traefik.http.services.fracdiff.loadbalancer.server.port=5000"
      - "traefik.docker.network=trade2026-frontend"

  # =========================================================================
  # Meta-Labeling Service (Port 5007)
  # =========================================================================
  meta-labeling:
    build:
      context: ../../backend
      dockerfile: Dockerfile.backend-service
      args:
        SERVICE_NAME: meta_labeling
    container_name: trade2026-meta-labeling
    hostname: trade2026-meta-labeling
    ports:
      - "5007:5000"
    networks:
      - frontend
      - backend
      - lowlatency
    environment:
      - SERVICE_NAME=Meta-Labeling
      - SERVICE_PORT=5000
      - QUESTDB_URL=http://questdb:9000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metalabel.rule=PathPrefix(`/api/metalabel`)"
      - "traefik.http.routers.metalabel.entrypoints=web"
      - "traefik.http.services.metalabel.loadbalancer.server.port=5000"
      - "traefik.docker.network=trade2026-frontend"

  # =========================================================================
  # Stock Screener Service (Port 5008)
  # =========================================================================
  stock-screener:
    build:
      context: ../../backend
      dockerfile: Dockerfile.backend-service
      args:
        SERVICE_NAME: stock_screener
    container_name: trade2026-stock-screener
    hostname: trade2026-stock-screener
    ports:
      - "5008:5000"
    networks:
      - frontend
      - backend
      - lowlatency
    environment:
      - SERVICE_NAME=Stock Screener
      - SERVICE_PORT=5000
      - QUESTDB_URL=http://questdb:9000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.screener.rule=PathPrefix(`/api/screener`) || PathPrefix(`/api/alpha`) || PathPrefix(`/api/regime`)"
      - "traefik.http.routers.screener.entrypoints=web"
      - "traefik.http.services.screener.loadbalancer.server.port=5000"
      - "traefik.docker.network=trade2026-frontend"

