# Sink Alt Configuration
# Phase 7B: Data Lake Sinks

# NATS Configuration
nats_url: "nats://nats:4222"
subject: "alt.norm.>"
queue_group: "sink-alt"

# Batching Configuration
batch_seconds: 10
max_batch: 2000
flush_on_shutdown: true

# Valkey/Redis Configuration
valkey_host: "valkey"
valkey_port: 6379
valkey_db: 1
dedup_ttl_hours: 72
lru_cache_size: 50000

# S3 Configuration (SeaweedFS)
s3:
  endpoint: "http://seaweedfs:8333"
  region: "us-east-1"
  access_key: "test"
  secret_key: "test"
  bucket: "trader2025"

# Delta Lake Configuration
delta:
  table_uri: "s3://trader2025/lake/alt_docs"
  partition_by: ["category", "dt"]
  compression: "zstd"
  enable_compaction: false
  small_file_target_mb: 256
  writer_threads: 2

# OpenSearch Configuration (optional)
opensearch:
  enabled: false
  url: "http://opensearch:9200"
  index: "alt_news"
  bulk_size: 100

# Service Configuration
health_port: 8112
metrics_port: 9112
log_level: "INFO"
log_format: "json"

# Performance Tuning
max_workers: 4
queue_size: 10000